-- Durable audit log for every betting signal decision.
-- Logs both BET and PASS outcomes for calibration, CLV, ROI and model drift analysis.

CREATE TABLE IF NOT EXISTS public.signal_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('OVER', 'UNDER', 'PASS')),
    should_bet BOOLEAN NOT NULL DEFAULT FALSE,
    model_total NUMERIC NOT NULL,
    raw_model_total NUMERIC NOT NULL,
    market_total NUMERIC NOT NULL,
    edge_runs NUMERIC NOT NULL,
    estimated_probability NUMERIC NOT NULL,
    break_even_probability NUMERIC NOT NULL,
    expected_value NUMERIC NOT NULL,
    stake NUMERIC NOT NULL DEFAULT 0,
    confidence TEXT NOT NULL CHECK (confidence IN ('LOW', 'MEDIUM', 'HIGH')),
    reason TEXT NOT NULL,
    calibration JSONB NOT NULL DEFAULT '{}'::jsonb,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_signal_decisions_game_id
    ON public.signal_decisions (game_id);

CREATE INDEX IF NOT EXISTS idx_signal_decisions_created_at
    ON public.signal_decisions (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_signal_decisions_should_bet
    ON public.signal_decisions (should_bet, created_at DESC);

ALTER TABLE public.signal_decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signal_decisions FORCE ROW LEVEL SECURITY;

-- No anon/authenticated policies by default.
-- Backend service role writes decisions through app/db/supabase_admin.py.
