-- Core tables for the MLB totals betting intelligence loop.

CREATE TABLE IF NOT EXISTS public.games (
    game_id TEXT PRIMARY KEY,
    game_date DATE,
    game_datetime TIMESTAMPTZ,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_probable_pitcher TEXT,
    away_probable_pitcher TEXT,
    status TEXT,
    home_runs INTEGER,
    away_runs INTEGER,
    total_runs INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.odds_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id TEXT,
    provider_game_id TEXT,
    home_team TEXT,
    away_team TEXT,
    bookmaker TEXT,
    line NUMERIC NOT NULL,
    over INTEGER NOT NULL,
    under INTEGER NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.game_results (
    game_id TEXT PRIMARY KEY REFERENCES public.games(game_id) ON DELETE CASCADE,
    home_runs INTEGER NOT NULL,
    away_runs INTEGER NOT NULL,
    total_runs INTEGER NOT NULL,
    finalized_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.model_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_version TEXT NOT NULL,
    rows_trained INTEGER NOT NULL,
    mae NUMERIC,
    rmse NUMERIC,
    clv_avg NUMERIC,
    roi NUMERIC,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_games_game_date ON public.games(game_date);
CREATE INDEX IF NOT EXISTS idx_odds_snapshots_game_id ON public.odds_snapshots(game_id);
CREATE INDEX IF NOT EXISTS idx_odds_snapshots_provider_game_id ON public.odds_snapshots(provider_game_id);
CREATE INDEX IF NOT EXISTS idx_odds_snapshots_timestamp ON public.odds_snapshots(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_model_runs_created_at ON public.model_runs(created_at DESC);

ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.games FORCE ROW LEVEL SECURITY;
ALTER TABLE public.odds_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.odds_snapshots FORCE ROW LEVEL SECURITY;
ALTER TABLE public.game_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_results FORCE ROW LEVEL SECURITY;
ALTER TABLE public.model_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.model_runs FORCE ROW LEVEL SECURITY;
