-- Time-consistent truth layer.
--
-- Purpose:
--   Link prediction timestamp, market snapshot timestamp, closing snapshot timestamp
--   and final result timestamp into one immutable evaluation record.
--
-- This prevents leakage by making every evaluation answerable from explicit timestamps:
--   1. What market line was known when the model predicted?
--   2. What closing line was used for CLV?
--   3. When was the final result / ground truth locked?

ALTER TABLE public.signal_decisions
    ADD COLUMN IF NOT EXISTS prediction_timestamp TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS market_snapshot_id BIGINT REFERENCES public.odds_snapshots(id),
    ADD COLUMN IF NOT EXISTS market_snapshot_timestamp TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS closing_snapshot_id BIGINT REFERENCES public.odds_snapshots(id),
    ADD COLUMN IF NOT EXISTS closing_snapshot_timestamp TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS result_finalized_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS truth_status TEXT NOT NULL DEFAULT 'PENDING'
        CHECK (truth_status IN ('PENDING', 'READY', 'VOID'));

CREATE TABLE IF NOT EXISTS public.prediction_truth_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_decision_id BIGINT NOT NULL REFERENCES public.signal_decisions(id) ON DELETE CASCADE,
    game_id TEXT NOT NULL,

    prediction_timestamp TIMESTAMPTZ NOT NULL,

    market_snapshot_id BIGINT NOT NULL REFERENCES public.odds_snapshots(id),
    market_snapshot_timestamp TIMESTAMPTZ NOT NULL,
    market_total NUMERIC NOT NULL,
    market_over INTEGER NOT NULL,
    market_under INTEGER NOT NULL,

    closing_snapshot_id BIGINT REFERENCES public.odds_snapshots(id),
    closing_snapshot_timestamp TIMESTAMPTZ,
    closing_total NUMERIC,
    closing_over INTEGER,
    closing_under INTEGER,

    result_finalized_at TIMESTAMPTZ,
    total_runs INTEGER,

    clv NUMERIC,
    truth_status TEXT NOT NULL DEFAULT 'PENDING'
        CHECK (truth_status IN ('PENDING', 'READY', 'VOID')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT prediction_truth_links_time_order CHECK (
        market_snapshot_timestamp <= prediction_timestamp
        AND (
            closing_snapshot_timestamp IS NULL
            OR closing_snapshot_timestamp >= prediction_timestamp
        )
        AND (
            result_finalized_at IS NULL
            OR result_finalized_at >= prediction_timestamp
        )
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_prediction_truth_links_signal_decision_id
    ON public.prediction_truth_links(signal_decision_id);

CREATE INDEX IF NOT EXISTS idx_prediction_truth_links_game_id
    ON public.prediction_truth_links(game_id);

CREATE INDEX IF NOT EXISTS idx_prediction_truth_links_truth_status
    ON public.prediction_truth_links(truth_status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_prediction_truth_links_prediction_timestamp
    ON public.prediction_truth_links(prediction_timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_signal_decisions_truth_status
    ON public.signal_decisions(truth_status, created_at DESC);

ALTER TABLE public.prediction_truth_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prediction_truth_links FORCE ROW LEVEL SECURITY;
